title: ELIXIR Training SPLASH
# This appears in the html browser tab for the site title (seen mostly by search engines, not users)

# topnav_title: ELIXIR Training SPLASH
# Optional: this appears on the top navigation bar next to the main_logo.svg icon
# description: "ELIXIR Training SPLASH"
# Metadata description of the website
remote_theme: ELIXIR-Belgium/elixir-toolkit-theme@2.3.0
repository: elixir-europe-training/ELIXIR-Training-SPLASH


# add gtag:

theme_variables:
  # ELIXIR blue
  theme_color: 205a86
  topnav:
    brand_logo: assets/img/main_logo.svg
  fonts:
    - https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,400;0,700;1,400;1,700&display=swap

exclude:
  - README.md
  - vendor
  - .gitignore
  - var/
  - Gemfile*
  - LICENSE

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      permalink: "/:basename"
      layout: "page"
      sidebar: main
  -
    scope:
      path: "pages/lifecycle"
    values:
      type: "pages"
      sidebar: lifecycle
  -
    scope:
      path: "pages/resources/resources.md"
    values:
      layout: "page"
      sidebar: resources
  -
    scope:
      path: "pages/resources"
    values:
      layout: "resource_page"
      sidebar: resources
  -
    scope:
      path: "pages/contribute"
    values:
      sidebar: contribute

  -
    scope:
      path: "pages/about"
    values:
      sidebar: about

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-github-metadata
  - jekyll-glossary_tooltip
  - webrick
